insert into user_tb(login_id, password, profile, nick_name, email, phone)
values ('ssar', '1234','/profileimg/man_img.png','hapssar', 'ssar@nate.com','010-1234-5678');

insert into festivalinfo_tb(content_id, title, content_type_id, event_start_date, event_end_date, event_place, sponsor1, sponsor1tel, sponsor2, sponsor2tel, zip_code, addr1, addr2, first_image, first_image2, home_page, img_name, info_name, overview, mapx, mapy, play_time, tel, tel_name, area_code, sigungu_code, origin_img_url, use_time_festival, info_text)
values ('3011530', '전주페스타', '15', '20241003', '20241026', '전주종합경기장', '전주시', '063-281-2960', '', '', '54894', '전북특별자치도 전주시 덕진구 기린대로 451 (덕진동1가)', '', 'http://tong.visitkorea.or.kr/cms/resource/25/3114125_image2_1.JPG', 'http://tong.visitkorea.or.kr/cms/resource/25/3114125_image3_1.JPG', '<a href=\"http://www.jeonjufesta.com/\" target=\"_blank\" title=\"새창 : 전주페스타 홈페이지 이동\">www.jeonjufesta.com</a>', '2024 전주페스타 1', '행사내용', '전주페스타는 맛, 멋, 열정을 담은 전주의 다양한 축제들을 모아, 10월 한 달간 선보이는 전주 통합축제로, 2024년에는 \"10월, 더 맛있는 전주!\"라는 슬로건 하에 문화도시 전주의 모든 것을 담아 전주종합경기장에서 10월 한 달간 개최된다. 전주를 대표하는 주요 축제들과 함께 전주페스타의 시작과 끝을 알리는 오프닝·클로징 무대, 전주 "맛" 콘텐츠, 전통놀이, 초대형 드론쇼, 레트로클럽, 술BOX 등  전주의 맛과 멋 그리고 열정을 보여주는 다채로운 콘텐츠를 10월 한 달간 매주 만나볼 수 있다.', '127.1274545926', '35.8405998309', '10:00~21:00', '063-281-2960', '전주시', '37', '12', 'http://tong.visitkorea.or.kr/cms/resource/17/3114117_image2_1.JPG', '무료', '1. 전주의 맛 <br>\n전주 대표음식 전주비빔밥을 비롯한 전주페스타 맛잔치·맛자랑 등 전주의 다양하고 맛있는 음식콘텐츠와 전주의 전통다과·디저트를 선보이는 대규모 "맛 스토어", 전주막걸리를 활용한 콘텐츠와 함께 "술BOX"에서 판매하는 다양한 우리 술까지, 한 달 내내 즐기는 전주의 맛 콘텐츠<br><br>\n2. 전주의 멋<br>\n전주 한지를 활용한 다양한 콘텐츠와 한지 의상 패션쇼, "책의 도시" 전주에서 즐기는 강연, 전시, 체험으로 가득한 독서 문화 콘텐츠와 함께 초대형 드론쇼, 전주페스타 예술콘서트, K-뮤지컬 마당창극 등 전주의 멋을 보여주는 특별한 콘텐츠<br><br>\n3. 전주의 열정·재미<br>\n전주페스타의 시작과 끝을 알리는 화려한 오프닝·클로징 공연, 조선팝의 본고장에서 즐기는 전통음악과 대중성을 접목한 "조선팝" 공연,\n전통놀이의 모든 것을 체험 가능한 전주페스타 우리놀이터, 전주 시민이 만드는 한바탕어울림공연 그리고 밤에도 잠들지 않는 레트로클럽까지 열정 가득한 전주페스타만의 콘텐츠\t');
insert into festivalinfo_tb(content_id, title, content_type_id, event_start_date, event_end_date, event_place, sponsor1, sponsor1tel, sponsor2, sponsor2tel, zip_code, addr1, addr2, first_image, first_image2, home_page, img_name, info_name, overview, mapx, mapy, play_time, tel, tel_name, area_code, sigungu_code, origin_img_url, use_time_festival, info_text)
values ('2753041', '피나클랜드 오천만송이 국화축제', '15', '20240914', '20241130', '피나클랜드', '(주)피나클랜드농업회사법인', '041-541-2582', '', '', '31428', '충청남도 아산시 영인면 월선길 20-42', '피나클랜드', 'http://tong.visitkorea.or.kr/cms/resource/40/3358740_image2_1.jpg', 'http://tong.visitkorea.or.kr/cms/resource/40/3358740_image3_1.jpg', '<a href=\"https://www.pinnacleland.co.kr/\" target=\"_blank\" title=\"새창 : 피나클랜드 국화축제\">https://www.pinnacleland.co.kr/</a>', '2024 피나클랜드 오천만송이 국화꽃향기 포스터', '행사내용', '피나클랜드에서 네번째로 선보이는 가을 오천만송이 국화축제에서 마을 주민들과 함께 직접 가꾼 억만송이의 다양한 가을꽃과 오천만송이 국화꽃이 피나클랜드를 가득 채운다. \n월선리를 의미하는 지름 5미터의 대형 국화 달 조형물을 비롯하여 국화터널, 국화탑 등 100여종의 국화 조형물 전시와 함께 다양한 가을꽃들로 가을의 정취를 느낄 수 있다. 주말에는 버블쇼, 사물놀이, 음악회 등 매주 다양한 이벤트를 진행한다.\n피나클랜드 내부의 카페 드 피나클에서는 봄꽃에이드, 봄꽃쌍화차 등 특별메뉴와 함께 먹거리장터에서는 다양한 음식들까지 준비되어 오감을 만족시켜준다. 볼거리, 먹을거리, 즐길거리 가득한 피나클랜드에서 가을을 즐길 수 있다.', '126.9263422708', '36.8725197718', '09:00~18:00', '041-541-2582', '(주)피나클랜드농업회사법인', '34', '9', 'http://tong.visitkorea.or.kr/cms/resource/39/3358739_image2_1.jpg', '유료<br>(평일)대인 13,000원 / 소인 11,000원<br> (주말,공휴일)대인 15,000원 / 소인 12,000원<br>소인 : 청소년/어린이/경로/장애인', '1. 메인프로그램 : 오천만송이 국화꽃향기 / 국화 대형 조형물 전시<br>\n2. 부대프로그램 : 버블쇼, 마술공연, 밴드공연 등 문화예술공연<br>\n3. 고객 참여 프로그램 : 알파카, 꽃사슴, 유산양 동물 먹이주기 체험 <br>\n4. 기타 내용 : 불꽃축제');
insert into festivalinfo_tb(content_id, title, content_type_id, event_start_date, event_end_date, event_place, sponsor1, sponsor1tel, sponsor2, sponsor2tel, zip_code, addr1, addr2, first_image, first_image2, home_page, img_name, info_name, overview, mapx, mapy, play_time, tel, tel_name, area_code, sigungu_code, origin_img_url, use_time_festival, info_text)
values ('631268', '한화와 함께하는 서울세계불꽃축제', '15', '20241005', '20241005', '여의도 한강공원 일대', '한화그룹, SBS', '02-519-9778', '(주) 한화,한화생명,한화손해보험,한화에어로스페이스,한화토탈에너지스,한화솔루션,한화투자증권,한화시스템,한화비전,한화임팩트,한화자산운용', '', '07337', '서울특별시 영등포구 여의동로 330 (여의도동)', '', 'http://tong.visitkorea.or.kr/cms/resource/77/3357677_image2_1.jpg', 'http://tong.visitkorea.or.kr/cms/resource/77/3357677_image3_1.jpg', '<a href=\"https://www.hanwhafireworks.com/kor/main.html\" target=\"_blank\" title=\"새창 : 한화와 함께하는 서울세계불꽃축제 홈페이지 이동\">www.hanwhafireworks.com</a>', '2024 한화와 함께하는 서울세계불꽃축제 포스터', '행사소개', '서울세계불꽃축제는 바쁜 매일을 살아가는 시민의 일상에 즐거움을 선사하기 위해 한화그룹에서 2000년부터 사회공헌 사업으로 꾸준히 진행해 온 축제이다.<br>매년 세계적인 수준의 불꽃 전문 기업들이 초청되어 여의도의 밤 하늘을 무대로 환상적인 불꽃 연출을 선보이며,<br>주간에도 다채로운 부대행사가 진행된다.<br>(주)한화가 자랑하는 멀티미디어 불꽃쇼는 불꽃과 음악, 레이저 연출이 결합된 아시아 최고 수준의 불꽃쇼이다.', '126.9336095794', '37.5263997727', '13:00~21:30', '02-519-9778', '한화그룹, SBS', '1', '20', 'http://tong.visitkorea.or.kr/cms/resource/78/3357678_image2_1.jpg', '무료 (일부 관람석 유료화)', '- 시민참여 프로그램<br>- 공식행사 및 불꽃쇼');

--insert into scrap_tb(is_scrap, user_id, content_content_id)
--values (true, 1, 2863965);
--insert into scrap_tb(is_scrap, user_id, content_content_id)
--values (true, 1, 2781669);

--insert into review_tb(user_id, is_deleted, context, content_id_content_id, rating, created_at)values(1, false, '22222', 126289, 4.5, now());
--insert into review_tb(user_id, is_deleted, context, content_id_content_id, rating, created_at)values(1, false, '감사합니다', 126289, 4, now());





-- insert into festivalinfo_tb (content_id, content_type_id) values (3021762, 15);
-- insert into festivalinfo_tb (content_id, content_type_id) values (3020141, 15);
--
--insert into review_tb(user_id, is_deleted, context, content_id_content_id, rating, created_at)values(1, false, '감사합니다',734219, 4.5, now());
-- insert into review_tb(user_id, is_deleted, context, content_id_content_id, festival_info_content_id, rating)
-- values(1,false, '감사합니다', 3021762, 3021762, 3.5);
-- insert into review_tb(user_id, is_deleted, context, content_id_content_id, festival_info_content_id, rating)
-- values(1,false, '안녕하세요', 3020141, 3020141, 5);